;;; Notes

(defun notes-find-file ()
  (interactive)
  (ido-find-file-in-dir "~/.notes"))
(defun notes-grep ()
  (interactive)
  (grep-compute-defaults)
  (rgrep (grep-read-regexp) "*.txt" "~/.notes")
  (switch-to-buffer-other-window "*grep*"))
(defun notes-log ()
  (interactive)
  (split-window-below 20)
  (find-file (format-time-string "~/.notes/log/%Y-%m-%d.txt")))
(defun notes-log-timestamp ()
  (interactive)
  (insert (format-time-string "%Y-%m-%d %a %I:%M %p\n")))

(define-prefix-command 'notes-map)
(global-set-key (kbd "C-c") 'notes-map)
(define-key notes-map (kbd "n z") 'notes-find-file)
(define-key notes-map (kbd "n f") 'notes-grep)
(define-key notes-map (kbd "n l") 'notes-log)
(define-key notes-map (kbd "n t") 'notes-log-timestamp)
